/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USER;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author SCC-COLLEGE
 */
    public class AddingInfo extends javax.swing.JFrame {

    /**
     * Creates new form admin_dashboard
     */
    public AddingInfo() {
        initComponents();
        fn.setBorder(new EmptyBorder(0,10,0,0));
        ln.setBorder(new EmptyBorder(0,10,0,0));
        mn.setBorder(new EmptyBorder(0,10,0,0));
        ln.setBorder(new EmptyBorder(0,10,0,0));
        address.setBorder(new EmptyBorder(0,10,0,0));
        occupation.setBorder(new EmptyBorder(0,10,0,0));
        religion.setBorder(new EmptyBorder(0,10,0,0));
    }
    
   
    Color Red = new Color(255,0,0);
    Color MainC = new Color(27,55,77);
    
    Color darktxt = new Color(27,57,77);
    Color Bluetxt = new Color(89,182,255);
    
    Color Panecolor = new Color(242,242,242);
    Color PaneNcolor = new Color(255,255,255);
    
      public static String email, usname;
      
      public String destination = "";
      File selectedFile;
      public String path;
      public String oldpath;
      
    
   public int FileExistenceChecker(String path){
        File file = new File(path);
        String fileName = file.getName();
        
        Path filePath = Paths.get("src/r_images", fileName);
        boolean fileExists = Files.exists(filePath);
        
        if (fileExists) {
            return 1;
        } else {
            return 0;
        }
    }

   public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            // Read the image file
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
            // Get the original width and height of the image
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
            // Calculate the new height based on the desired width and the aspect ratio
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }
   
   public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}

         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        household = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        a10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        fn1 = new javax.swing.JTextField();
        a12 = new javax.swing.JLabel();
        fn2 = new javax.swing.JTextField();
        fn3 = new javax.swing.JTextField();
        a13 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        fn4 = new javax.swing.JTextField();
        a15 = new javax.swing.JLabel();
        fn5 = new javax.swing.JTextField();
        a17 = new javax.swing.JLabel();
        fn6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fn7 = new javax.swing.JTextField();
        a18 = new javax.swing.JLabel();
        fn8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fn9 = new javax.swing.JTextField();
        fn10 = new javax.swing.JTextField();
        fn11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        a20 = new javax.swing.JLabel();
        a21 = new javax.swing.JLabel();
        a22 = new javax.swing.JLabel();
        a23 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        a25 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        a26 = new javax.swing.JLabel();
        a27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a28 = new javax.swing.JLabel();
        a29 = new javax.swing.JLabel();
        a30 = new javax.swing.JLabel();
        a31 = new javax.swing.JLabel();
        a32 = new javax.swing.JLabel();
        a33 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        d = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 235)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setBackground(new java.awt.Color(27, 55, 77));
        Add.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        Add.setText("Add Resident");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel3.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 200, 50));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 55, 77));
        jLabel8.setText("HouseHold");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 100, 30));

        ln.setBackground(new java.awt.Color(245, 246, 248));
        ln.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        ln.setForeground(new java.awt.Color(100, 115, 122));
        ln.setBorder(null);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel3.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 55, 77));
        jLabel4.setText("Middle Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        sex.setBackground(new java.awt.Color(245, 246, 248));
        sex.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        sex.setForeground(new java.awt.Color(100, 115, 122));
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Select", "Male", "Female" }));
        sex.setBorder(null);
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        jPanel3.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 200, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 55, 77));
        jLabel7.setText("Date of Birth ( yy-mm-day )");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, 30));

        a4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 0, 0));
        a4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a4.setText("*");
        jPanel3.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 40));

        a3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 0, 0));
        a3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a3.setText("*");
        jPanel3.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 30));

        a1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 0, 0));
        a1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a1.setText("*");
        jPanel3.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2360, 480, 110, 30));

        a2.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 0, 0));
        a2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a2.setText("*");
        jPanel3.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 140, 40));

        household.setBackground(new java.awt.Color(245, 246, 248));
        household.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        household.setForeground(new java.awt.Color(100, 115, 122));
        household.setBorder(null);
        household.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                householdActionPerformed(evt);
            }
        });
        jPanel3.add(household, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 200, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(27, 55, 77));
        jLabel10.setText("Sex");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 30, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 55, 77));
        jLabel11.setText("Nationality");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 20));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 55, 77));
        jLabel12.setText("Head of the Family:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        a7.setForeground(new java.awt.Color(255, 0, 0));
        a7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a7.setText("*");
        jPanel3.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 520, 120, 30));

        fn.setBackground(new java.awt.Color(245, 246, 248));
        fn.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn.setForeground(new java.awt.Color(100, 115, 122));
        fn.setBorder(null);
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel3.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 40));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(27, 55, 77));
        jLabel13.setText("First Name");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 30));

        status.setBackground(new java.awt.Color(245, 246, 248));
        status.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        status.setForeground(new java.awt.Color(100, 115, 122));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Select", "Single", "Married", "Widowed", "Separated" }));
        status.setBorder(null);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 200, 40));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(27, 55, 77));
        jLabel14.setText("Civil Status");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 30));

        a10.setForeground(new java.awt.Color(255, 0, 0));
        a10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a10.setText("*");
        jPanel3.add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 130, 30));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(27, 55, 77));
        jLabel15.setText("Occupation");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, 30));

        a8.setForeground(new java.awt.Color(255, 0, 0));
        a8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a8.setText("*");
        jPanel3.add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 140, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(27, 55, 77));
        jLabel16.setText("Religion");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 70, 30));

        a9.setForeground(new java.awt.Color(255, 0, 0));
        a9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a9.setText("*");
        jPanel3.add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 55, 77));
        jLabel2.setText("Registered Voter");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 55, 77));
        jLabel3.setText("Age");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 55, 77));
        jLabel6.setText("Gender");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(27, 55, 77));
        jLabel9.setText("Income/per Month");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("With Birth Certificate");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 200, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(27, 55, 77));
        jLabel18.setText("Last Name");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 30));

        a11.setForeground(new java.awt.Color(255, 0, 0));
        a11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a11.setText("*");
        jPanel3.add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 120, 40));

        fn1.setBackground(new java.awt.Color(245, 246, 248));
        fn1.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn1.setForeground(new java.awt.Color(100, 115, 122));
        fn1.setBorder(null);
        fn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn1ActionPerformed(evt);
            }
        });
        jPanel3.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 40));

        a12.setForeground(new java.awt.Color(255, 0, 0));
        a12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a12.setText("*");
        jPanel3.add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, 40));

        fn2.setBackground(new java.awt.Color(245, 246, 248));
        fn2.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn2.setForeground(new java.awt.Color(100, 115, 122));
        fn2.setBorder(null);
        fn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn2ActionPerformed(evt);
            }
        });
        jPanel3.add(fn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, 40));

        fn3.setBackground(new java.awt.Color(245, 246, 248));
        fn3.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn3.setForeground(new java.awt.Color(100, 115, 122));
        fn3.setBorder(null);
        fn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn3ActionPerformed(evt);
            }
        });
        jPanel3.add(fn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 200, 40));

        a13.setForeground(new java.awt.Color(255, 0, 0));
        a13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a13.setText("*");
        jPanel3.add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 120, 40));

        a14.setForeground(new java.awt.Color(255, 0, 0));
        a14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a14.setText("*");
        jPanel3.add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 120, 40));

        fn4.setBackground(new java.awt.Color(245, 246, 248));
        fn4.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn4.setForeground(new java.awt.Color(100, 115, 122));
        fn4.setBorder(null);
        fn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn4ActionPerformed(evt);
            }
        });
        jPanel3.add(fn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 200, 40));

        a15.setForeground(new java.awt.Color(255, 0, 0));
        a15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a15.setText("*");
        jPanel3.add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 120, 40));

        fn5.setBackground(new java.awt.Color(245, 246, 248));
        fn5.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn5.setForeground(new java.awt.Color(100, 115, 122));
        fn5.setBorder(null);
        fn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn5ActionPerformed(evt);
            }
        });
        jPanel3.add(fn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 200, 40));

        a17.setForeground(new java.awt.Color(255, 0, 0));
        a17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a17.setText("*");
        jPanel3.add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 120, 40));

        fn6.setBackground(new java.awt.Color(245, 246, 248));
        fn6.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn6.setForeground(new java.awt.Color(100, 115, 122));
        fn6.setBorder(null);
        fn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn6ActionPerformed(evt);
            }
        });
        jPanel3.add(fn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 200, 40));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(27, 55, 77));
        jLabel19.setText("Status");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 20));

        fn7.setBackground(new java.awt.Color(245, 246, 248));
        fn7.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn7.setForeground(new java.awt.Color(100, 115, 122));
        fn7.setBorder(null);
        fn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn7ActionPerformed(evt);
            }
        });
        jPanel3.add(fn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 200, 40));

        a18.setForeground(new java.awt.Color(255, 0, 0));
        a18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a18.setText("*");
        jPanel3.add(a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 40));

        fn8.setBackground(new java.awt.Color(245, 246, 248));
        fn8.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn8.setForeground(new java.awt.Color(100, 115, 122));
        fn8.setBorder(null);
        fn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn8ActionPerformed(evt);
            }
        });
        jPanel3.add(fn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 200, 40));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(27, 55, 77));
        jLabel20.setText("Status");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 20));

        fn9.setBackground(new java.awt.Color(245, 246, 248));
        fn9.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn9.setForeground(new java.awt.Color(100, 115, 122));
        fn9.setBorder(null);
        fn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn9ActionPerformed(evt);
            }
        });
        jPanel3.add(fn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 200, 40));

        fn10.setBackground(new java.awt.Color(245, 246, 248));
        fn10.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn10.setForeground(new java.awt.Color(100, 115, 122));
        fn10.setBorder(null);
        fn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn10ActionPerformed(evt);
            }
        });
        jPanel3.add(fn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 200, 40));

        fn11.setBackground(new java.awt.Color(245, 246, 248));
        fn11.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        fn11.setForeground(new java.awt.Color(100, 115, 122));
        fn11.setBorder(null);
        fn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn11ActionPerformed(evt);
            }
        });
        jPanel3.add(fn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 200, 40));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(27, 55, 77));
        jLabel21.setText("Middle Name");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(27, 55, 77));
        jLabel22.setText("Date of Birth ( yy-mm-day )");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, 30));

        a20.setForeground(new java.awt.Color(255, 0, 0));
        a20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a20.setText("*");
        jPanel3.add(a20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        a21.setForeground(new java.awt.Color(255, 0, 0));
        a21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a21.setText("*");
        jPanel3.add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 30));

        a22.setForeground(new java.awt.Color(255, 0, 0));
        a22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a22.setText("*");
        jPanel3.add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(2360, 480, 110, 30));

        a23.setForeground(new java.awt.Color(255, 0, 0));
        a23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a23.setText("*");
        jPanel3.add(a23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 140, 40));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(27, 55, 77));
        jLabel23.setText("Sex");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 30, 30));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(27, 55, 77));
        jLabel24.setText("Middle Name");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        a25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        a25.setForeground(new java.awt.Color(255, 0, 0));
        a25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a25.setText("*");
        jPanel3.add(a25, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 140, 30));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(27, 55, 77));
        jLabel25.setText("Date of Birth ( yy-mm-day )");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, 30));

        a26.setForeground(new java.awt.Color(255, 0, 0));
        a26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a26.setText("*");
        jPanel3.add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        a27.setForeground(new java.awt.Color(255, 0, 0));
        a27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a27.setText("*");
        jPanel3.add(a27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 30));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(27, 55, 77));
        jLabel26.setText("Middle Name");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        a28.setForeground(new java.awt.Color(255, 0, 0));
        a28.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a28.setText("*");
        jPanel3.add(a28, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 140, 30));

        a29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        a29.setForeground(new java.awt.Color(255, 0, 0));
        a29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a29.setText("*");
        jPanel3.add(a29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 140, 30));

        a30.setForeground(new java.awt.Color(255, 0, 0));
        a30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a30.setText("*");
        jPanel3.add(a30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        a31.setForeground(new java.awt.Color(255, 0, 0));
        a31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a31.setText("*");
        jPanel3.add(a31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 30));

        a32.setForeground(new java.awt.Color(255, 0, 0));
        a32.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a32.setText("*");
        jPanel3.add(a32, new org.netbeans.lib.awtextra.AbsoluteConstraints(2360, 480, 110, 30));

        a33.setForeground(new java.awt.Color(255, 0, 0));
        a33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        a33.setText("*");
        jPanel3.add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 140, 40));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(27, 55, 77));
        jLabel27.setText("Sex");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 30, 30));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(27, 55, 77));
        jLabel28.setText("Nationality");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 20));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(27, 55, 77));
        jLabel29.setText("Head of the Family:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 60, 1310, 740);

        jPanel6.setBackground(new java.awt.Color(27, 55, 77));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d.setBackground(new java.awt.Color(244, 244, 244));
        d.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        d.setForeground(new java.awt.Color(204, 204, 204));
        d.setText("Resident's purok address will be automatically set for every household. ");
        jPanel6.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESIDENTS INFORMATION");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 1310, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    Session sess = Session.getInstance();
       
   try {
    dbConnector dbc = new dbConnector();
    ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_id = '"+sess.getUid()+"'");
    ResultSet rs1 = dbc.getData("SELECT h_name FROM tbl_household");
  

    if(rs.next()){
       
        Vector<String> householdIDs = new Vector<>();
 
        
        householdIDs.add("Select household");  
       
        while(rs1.next()) {
            householdIDs.add(rs1.getString("h_name"));
        }
        
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(householdIDs);
        household.setModel(model);
        

        rs.close();
        rs1.close();
    }
} catch(SQLException ex) {
    System.out.println(""+ex);
}

    }//GEN-LAST:event_formWindowActivated

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        
    Session sess = Session.getInstance();

    int userID = sess.getUid();    
        
    a1.setText("");
    a2.setText("");
    a3.setText("");
    a4.setText("");
    a5.setText("");
    a6.setText("");
    a7.setText("");
    a8.setText("");
    a9.setText("");
    a10.setText("");

    if (ln.getText().isEmpty() || fn.getText().isEmpty() || mn.getText().isEmpty() 
        || address.getText().isEmpty() || occupation.getText().isEmpty() 
        || religion.getText().isEmpty() || dob.getDate() == null
        || sex.getSelectedIndex() == 0 || status.getSelectedIndex() == 0 
        || household.getSelectedIndex() == 0) {

        if (ln.getText().isEmpty()) {
            a1.setText("*");
        }
        if (fn.getText().isEmpty()) {
            a2.setText("*");
        }
        if (mn.getText().isEmpty()) {
            a3.setText("*");
        }
        if (address.getText().isEmpty()) {
            a4.setText("*");
        } 
        if (occupation.getText().isEmpty()) {
            a5.setText("*");
        }  
        if (religion.getText().isEmpty()) {
            a6.setText("*");
        }
        if (dob.getDate() == null) {
            a7.setText("*");
        }
        if (sex.getSelectedIndex() == 0) {
            a8.setText("*");
        }
        if (status.getSelectedIndex() == 0) {
            a9.setText("*");
        }
        if (household.getSelectedIndex() == 0) {
            a10.setText("*");
        }

    } else {

        dbConnector dbc = new dbConnector();

        String imageDestination = (selectedFile != null) ? destination : "src/u_default/blank_pfp.jpg";
        String selectedHousehold = household.getSelectedItem().toString();

        if (selectedHousehold.equals("Select household")) {
            a10.setText("Select a valid household");
        } else {
            try {
                String query = "SELECT h_id FROM tbl_household WHERE h_name = ?";
                PreparedStatement pst = dbc.connect.prepareStatement(query);
                pst.setString(1, selectedHousehold);

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    int householdId = rs.getInt("h_id");

                    try (PreparedStatement insertPst = dbc.connect.prepareStatement(
                        "INSERT INTO tbl_residents (r_lname, r_fname, r_mname, r_address, r_sex, r_dob, r_civilstatus, r_occupation, r_religion, h_id, r_image, r_status) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")) {

                        insertPst.setString(1, ln.getText());
                        insertPst.setString(2, fn.getText());
                        insertPst.setString(3, mn.getText());
                        insertPst.setString(4, address.getText());
                        insertPst.setString(5, sex.getSelectedItem().toString());
                        insertPst.setString(6, new SimpleDateFormat("yyyy-MM-dd").format(dob.getDate()));
                        insertPst.setString(7, status.getSelectedItem().toString());
                        insertPst.setString(8, occupation.getText());
                        insertPst.setString(9, religion.getText());
                        insertPst.setInt(10, householdId);
                        insertPst.setString(11, imageDestination);
                        insertPst.setString(12, "Active");

                        int rowsInserted = insertPst.executeUpdate();
                        
                        ResultSet generatedKeys = pst.getGeneratedKeys();
                            if (generatedKeys.next()) {
                                int newResidentId = generatedKeys.getInt(1);
                                logEvent(userID, "IMPORT_NEW_RESIDENT", "Resident ID: " + newResidentId + " is added by user.");
                            }
                        
                        if (rowsInserted > 0) {
                            if (selectedFile != null) {
                                try {
                                    Files.copy(selectedFile.toPath(), new File(destination).toPath(), StandardCopyOption.REPLACE_EXISTING);
                                } catch (IOException ex) {
                                    System.out.println("Insert Image Error: " + ex);
                                }
                            }


                            String updateQuery = "UPDATE tbl_barangay SET b_population = b_population + 1 WHERE b_id = ?";
                            PreparedStatement updatePst = dbc.connect.prepareStatement(updateQuery);
                            updatePst.setInt(1, 1001);
                            updatePst.executeUpdate();
                            updatePst.close();

                            JOptionPane.showMessageDialog(null, "Resident Registered Successfully!");
                            User_Residents au = new User_Residents();
                            au.setVisible(true);
                            this.dispose();
                        } else {
                            System.out.println("Error inserting data");
                        }

                    } catch (SQLException ex) {
                        System.out.println("Database Error: " + ex.getMessage());
                    }

                } else {
                    a10.setText("Invalid Household Selection");
                }

                rs.close();
                pst.close();

            } catch (SQLException ex) {
                System.out.println("Database Error: " + ex.getMessage());
            }
        }
    }

    }//GEN-LAST:event_AddActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void householdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_householdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_householdActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void fn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn1ActionPerformed

    private void fn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn2ActionPerformed

    private void fn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn3ActionPerformed

    private void fn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn4ActionPerformed

    private void fn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn5ActionPerformed

    private void fn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn6ActionPerformed

    private void fn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn7ActionPerformed

    private void fn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn8ActionPerformed

    private void fn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn9ActionPerformed

    private void fn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn10ActionPerformed

    private void fn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn11ActionPerformed

     public void logEvent(int userId, String event, String description) {
   
        dbConnector dbc = new dbConnector();
        PreparedStatement pstmt = null;
        
    try {
     

        String sql = "INSERT INTO tbl_logs (l_timestamp, l_event, u_id, l_description) VALUES (?, ?, ?, ?)";
        pstmt = dbc.connect.prepareStatement(sql);
        pstmt.setTimestamp(1, new Timestamp(new java.util.Date().getTime()));
        pstmt.setString(2, event);
        pstmt.setInt(3, userId);
        pstmt.setString(4, description);

        pstmt.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
       
    }
    
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a15;
    private javax.swing.JLabel a17;
    private javax.swing.JLabel a18;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a20;
    private javax.swing.JLabel a21;
    private javax.swing.JLabel a22;
    private javax.swing.JLabel a23;
    private javax.swing.JLabel a25;
    private javax.swing.JLabel a26;
    private javax.swing.JLabel a27;
    private javax.swing.JLabel a28;
    private javax.swing.JLabel a29;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a30;
    private javax.swing.JLabel a31;
    private javax.swing.JLabel a32;
    private javax.swing.JLabel a33;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    public javax.swing.JLabel d;
    public javax.swing.JTextField fn;
    public javax.swing.JTextField fn1;
    public javax.swing.JTextField fn10;
    public javax.swing.JTextField fn11;
    public javax.swing.JTextField fn2;
    public javax.swing.JTextField fn3;
    public javax.swing.JTextField fn4;
    public javax.swing.JTextField fn5;
    public javax.swing.JTextField fn6;
    public javax.swing.JTextField fn7;
    public javax.swing.JTextField fn8;
    public javax.swing.JTextField fn9;
    public javax.swing.JComboBox<String> household;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JTextField ln;
    public javax.swing.JComboBox<String> sex;
    public javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
